### ISSUE TITLE
Access to DTLS identity information when answering a request

### ISSUE THREAD

**Issue by jvermillard** [eclipse/californium.core#13]
I use californium with scandium for security. 
I want to implement some ACL or behavior based on the identity used for the DTLS authentication (PSK identity, or the public key or certificate).
For that I need to be able to retrive DTLS session identity information from the CoapExchange or Request object passed to the handleXXX() methods.

**Comment by sophokles73** [comment]
@jvermillard,

Californium 1.0.0 provides accessors for retrieving the peer's identity from the CoAP Request object.
Can we close this?

Kai

**Comment by jvermillard** [comment]
yes
