### ISSUE TITLE
Illegal record content type error while using Cf-secure project

### ISSUE THREAD

**Issue by kuriakosejohn** [eclipse/californium.core#20]
I always get the following error while using cf-secure, was trying to setup a CoAP server with DTLS

14 WARNING [Record]: Received illegal record content type: 68 - (ch.ethz.inf.vs.scandium.dtls.Record.java:192) fromByteArray() in thread DTLS-Receiver0.0.0.0/0.0.0.0:5683 at (2014-09-28 13:53:13)

**Comment by sophokles73** [comment]
The ''cf-secure'' module contains examples for both a secure client as well as a secure server which illustrate how to set up security at both ends.
